// This file is generated by scripts/buildStudioSnapshot.mjs.
// Do not edit by hand; update the CAD status source files or the snapshot builder.

export const generatedSnapshot = {
  "generatedAt": "2026-05-15T23:31:39.314Z",
  "sourcePaths": {
    "appRoot": "D:\\Winnsen_Structure_Agent_Studio",
    "cadWorkspace": "D:\\机械结构工程师智能体",
    "intakeStatus": "D:\\机械结构工程师智能体\\outputs\\intake\\intake_pipeline_status_v1.md",
    "outdoorStatus": "D:\\机械结构工程师智能体\\outputs\\intake\\outdoor_courier_family_intake_status.md",
    "strictQueueCsv": "D:\\机械结构工程师智能体\\outputs\\freecad\\locker_16029_strict_geometry_upgrade_queue.csv",
    "strictQueueMd": "D:\\机械结构工程师智能体\\outputs\\freecad\\locker_16029_strict_geometry_upgrade_queue.md",
    "outdoorGateCsv": "D:\\机械结构工程师智能体\\outputs\\freecad\\outdoor_courier_production_gate_queue.csv",
    "outdoorGateMd": "D:\\机械结构工程师智能体\\outputs\\freecad\\outdoor_courier_production_gate_queue.md",
    "outdoorSingleDoorAudit": "D:\\机械结构工程师智能体\\outputs\\freecad\\outdoor_courier_single_door\\outdoor_courier_waterproof_door_1_12_R_single_panel_v1_source_signature_audit.md"
  },
  "sources": [
    {
      "path": "D:\\机械结构工程师智能体\\outputs\\intake\\intake_pipeline_status_v1.md",
      "updatedAt": "2026-05-15T14:45:26.986Z",
      "bytes": 18940
    },
    {
      "path": "D:\\机械结构工程师智能体\\outputs\\intake\\outdoor_courier_family_intake_status.md",
      "updatedAt": "2026-05-15T14:44:22.466Z",
      "bytes": 9398
    },
    {
      "path": "D:\\机械结构工程师智能体\\outputs\\freecad\\locker_16029_strict_geometry_upgrade_queue.csv",
      "updatedAt": "2026-05-15T09:24:19.063Z",
      "bytes": 827647
    },
    {
      "path": "D:\\机械结构工程师智能体\\outputs\\freecad\\locker_16029_strict_geometry_upgrade_queue.md",
      "updatedAt": "2026-05-15T09:24:19.063Z",
      "bytes": 4299
    },
    {
      "path": "D:\\机械结构工程师智能体\\outputs\\freecad\\outdoor_courier_production_gate_queue.csv",
      "updatedAt": "2026-05-15T14:41:40.950Z",
      "bytes": 137151
    },
    {
      "path": "D:\\机械结构工程师智能体\\outputs\\freecad\\outdoor_courier_production_gate_queue.md",
      "updatedAt": "2026-05-15T14:41:40.951Z",
      "bytes": 11029
    },
    {
      "path": "D:\\机械结构工程师智能体\\outputs\\freecad\\outdoor_courier_single_door\\outdoor_courier_waterproof_door_1_12_R_single_panel_v1_source_signature_audit.md",
      "updatedAt": "2026-05-15T15:08:46.265Z",
      "bytes": 1426
    }
  ],
  "summary": {
    "projectSlots": 6,
    "activeProjects": 2,
    "futureSlots": 2,
    "reservedFamilies": 2,
    "cadEvidenceAssetsLabel": "2,000+",
    "productionCandidateRows": 0
  },
  "projects": {
    "locker16029": {
      "indexedFiles": 1385,
      "sourceAssemblies": 149,
      "sourceParts": 500,
      "sourceDrawings": 342,
      "dxfFiles": 142,
      "dxfParsed": 142,
      "bomRows": 134,
      "bomMapped": 134,
      "swEvidenceRows": 206,
      "strictRows": 1504,
      "strictPriorityCounts": {
        "P0": 0,
        "P1": 1467,
        "P2": 37,
        "P3": 0
      },
      "strictModuleCounts": {
        "ordinary_door": 356,
        "cabinet_body": 104,
        "door_frame": 68,
        "hinge_system": 584,
        "lock_system": 392
      },
      "regressionStatus": "PASS",
      "verifiedCases": [
        "8door",
        "12door",
        "14door",
        "18door_W784"
      ]
    },
    "outdoorCourier": {
      "sourceRoot": "C:\\Users\\Administrator\\Desktop\\户外柜参数化模板素材",
      "activeProjectCount": 4,
      "dxfParsed": 283,
      "dxfTotal": 283,
      "bomMapped": 611,
      "bomRows": 611,
      "familyRuleCandidates": 611,
      "familyRuleFamilies": 25,
      "stepQueueRows": 77,
      "stepExportedOrExisting": 67,
      "stepExportFailed": 10,
      "measuredValidStepRows": 67,
      "formedBboxMeasuredRows": 131,
      "productionGateRows": 199,
      "releaseStatusCounts": {
        "step_export_failed": 32,
        "step_invalid": 1,
        "missing_step_export": 35,
        "formed_step_bbox_measured": 131
      },
      "gateCounts": {
        "p0_step_export_blocker_door_panel": 20,
        "p0_step_export_blocker_lock_or_water_guide": 12,
        "p1_external_or_invalid_step_review": 1,
        "p1_missing_step_export_door_lock": 9,
        "p2_missing_step_export_body_or_base": 24,
        "p2_missing_step_export_operation_panel": 1,
        "p2_missing_step_export_other": 1,
        "p3_measured_door_panel_semantic_gate": 52,
        "p3_measured_door_lock_semantic_gate": 37,
        "p3_measured_outdoor_canopy_semantic_gate": 22,
        "p3_measured_operation_panel_semantic_gate": 20
      },
      "p0Blockers": 32,
      "singleDoorAuditStatus": "PASS_BBOX_ONLY_NEEDS_TOPOLOGY_UPGRADE"
    }
  }
} as const
