using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Management;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;

namespace Winnsen.StructureAgent.Native888
{
    internal static class InspectAssemblyTongues888x14
    {
        private const string ToolId="native_assembly_tongue_inspector_888x14_v1";
        private const string ExpectedSourceSha256="__SOURCE_SHA256__";
        private const string TongueName="锁舌.SLDPRT";
        private const string TongueSha="26603389858218CE45164EEA57294016830D671B00B689982B1483B1FDE7E719";
        private const string SwPath=@"D:\soildworks2020\SOLIDWORKS\SLDWORKS.exe";
        private const string SwSha="1318AE1BE2F1B06AD360938760217378582B6FCA95CC2B2EB181C21262948978";
        [STAThread]
        private static int Main(string[] args)
        {
            if(args.Length==1&&args[0]=="--identity"){Console.WriteLine("sourceNormalizedSha256="+ExpectedSourceSha256);Console.WriteLine("executableSha256="+Hash(System.Reflection.Assembly.GetExecutingAssembly().Location));return 0;}
            if(args.Length==1&&args[0]=="--self-test"){Console.WriteLine("{\"selfTest\":\"PASS\",\"solidWorksStarted\":false,\"toolId\":\""+ToolId+"\"}");return 0;}
            if(args.Length!=3){Console.Error.WriteLine("Usage: InspectAssemblyTongues888x14.exe <attempt-root> <build-evidence-sha256> <part-inspector-evidence-sha256>");return 2;}
            string attempt=Path.GetFullPath(args[0]).TrimEnd('\\'), evidenceDir=Path.Combine(attempt,"evidence"), cad=Path.Combine(attempt,@"native_cad\working_pack");
            string build=Path.Combine(evidenceDir,"lock_topology_888x14.v2.json"), inspector=Path.Combine(evidenceDir,"lock_topology_888x14.inspector.v1.json"), manifest=Path.Combine(evidenceDir,"root_assembly_888x14.v1.json"), output=Path.Combine(evidenceDir,"assembly_lock_tongues_888x14.json");
            if(!File.Exists(build)||!File.Exists(inspector)||!File.Exists(manifest)||File.Exists(output)||Hash(build)!=args[1].ToUpperInvariant()||Hash(inspector)!=args[2].ToUpperInvariant()||Process.GetProcessesByName("SLDWORKS").Length!=0||Process.GetProcessesByName("sldProcMon").Length!=0)return 3;
            string exe=System.Reflection.Assembly.GetExecutingAssembly().Location, source=Path.GetFullPath(Path.Combine(Path.GetDirectoryName(exe),"..","InspectAssemblyTongues888x14.cs"));if(!Normalized(source).Equals(ExpectedSourceSha256,StringComparison.OrdinalIgnoreCase))return 4;
            var manifestDoc=new JavaScriptSerializer().DeserializeObject(File.ReadAllText(manifest,Encoding.UTF8)) as Dictionary<string,object>;if(manifestDoc==null||!Exact(manifestDoc,"schema","task","recipe","plan","tool","evidence","rootAssembly","generatedAtUtc")||Convert.ToString(manifestDoc["schema"])!="winnsen.locker16029.native_888x14_root_assembly_manifest.v1")return 5;
            var manifestTask=manifestDoc["task"] as Dictionary<string,object>;var manifestRecipe=manifestDoc["recipe"] as Dictionary<string,object>;var manifestPlan=manifestDoc["plan"] as Dictionary<string,object>;var manifestTool=manifestDoc["tool"] as Dictionary<string,object>;var manifestEvidence=manifestDoc["evidence"] as Dictionary<string,object>;var rootInfo=manifestDoc["rootAssembly"] as Dictionary<string,object>;
            if(manifestTask==null||!Exact(manifestTask,"id","revision","digest")||manifestRecipe==null||!Exact(manifestRecipe,"id","version","digest")||manifestPlan==null||!Exact(manifestPlan,"sha256")||manifestTool==null||!Exact(manifestTool,"id","sourceNormalizedSha256","executableSha256")||Convert.ToString(manifestTool["id"])!="native_root_assembly_888x14_v1"||manifestEvidence==null||!Exact(manifestEvidence,"path","sha256")||rootInfo==null||!Exact(rootInfo,"path","sha256"))return 5;
            string rootStageEvidence=Path.GetFullPath(Convert.ToString(manifestEvidence["path"]));if(!Under(rootStageEvidence,evidenceDir)||!File.Exists(rootStageEvidence)||Hash(rootStageEvidence)!=Convert.ToString(manifestEvidence["sha256"]).ToUpperInvariant())return 5;string root=Path.GetFullPath(Convert.ToString(rootInfo["path"]));if(!Under(root,cad)||!File.Exists(root)||Path.GetExtension(root).ToLowerInvariant()!=".sldasm"||Hash(root)!=Convert.ToString(rootInfo["sha256"]).ToUpperInvariant())return 5;
            ISldWorks sw=null;int pid=0;long ticks=0;var monitors=new List<Dictionary<string,object>>();var rows=new List<Dictionary<string,object>>();int errors=0,warnings=0;bool rebuilt=false;string before=Hash(root);string revision="",swExe="";
            try{sw=Activator.CreateInstance(Type.GetTypeFromProgID("SldWorks.Application.28",true)) as ISldWorks;if(sw==null)return 10;sw.Visible=false;sw.UserControl=false;sw.CommandInProgress=true;pid=sw.GetProcessID();ticks=Process.GetProcessById(pid).StartTime.ToUniversalTime().Ticks;revision=sw.RevisionNumber();swExe=Process.GetProcessById(pid).MainModule.FileName;if(!revision.StartsWith("28.")||!Same(swExe,SwPath)||Hash(swExe)!=SwSha)return 11;Thread.Sleep(750);monitors=OwnedMonitors(pid);
                ModelDoc2 model=sw.OpenDoc6(root,(int)swDocumentTypes_e.swDocASSEMBLY,(int)swOpenDocOptions_e.swOpenDocOptions_Silent|(int)swOpenDocOptions_e.swOpenDocOptions_ReadOnly,"",ref errors,ref warnings) as ModelDoc2;if(model==null||errors!=0||warnings!=0)return 12;rebuilt=model.ForceRebuild3(false);AssemblyDoc assembly=model as AssemblyDoc;Array components=assembly.GetComponents(false) as Array;var instanceKeys=new HashSet<string>(StringComparer.OrdinalIgnoreCase);if(components!=null)foreach(object item in components){Component2 c=item as Component2;string path=Path.GetFullPath(c.GetPathName()??"");if(Path.GetFileName(path).Equals(TongueName,StringComparison.OrdinalIgnoreCase)&&File.Exists(path)&&Hash(path)==TongueSha){string instanceKey=c.GetSelectByIDString();if(!instanceKeys.Add(instanceKey))throw new InvalidOperationException("duplicate recursive tongue component instance");MathTransform tr=c.Transform2;double[] a=tr==null?null:tr.ArrayData as double[];if(a==null||a.Length<13)throw new InvalidOperationException("Transform2 unavailable");double[] rotation=a.Take(9).ToArray();double[] xyz=new[]{a[9]*1000,a[10]*1000,a[11]*1000};string side=xyz[0]<0?"L":"R";double[] ys=Enumerable.Range(0,7).Select(i=>32+(((12.0/7.0)*152.5-7)/2)+i*((12.0/7.0)*152.5)).ToArray();int row=Enumerable.Range(0,7).OrderBy(i=>Math.Abs(ys[i]-xyz[1])).First()+1;rows.Add(new Dictionary<string,object>{{"component_name",c.Name2},{"component_instance_path",instanceKey},{"source_path",path},{"source_sha256",TongueSha},{"side",side},{"row_index",row},{"translation_mm",xyz},{"rotation",rotation},{"suppressed",c.IsSuppressed()},{"hidden",c.IsHidden(true)}});Release(tr);}Release(c);}if(rows.Count!=14||instanceKeys.Count!=14)throw new InvalidOperationException("recursive assembly must contain exactly 14 unique tongue instances");string title=model.GetTitle();Release(model);sw.CloseDoc(title);
            }finally{if(sw!=null){try{sw.CloseAllDocuments(true);sw.CommandInProgress=false;sw.ExitApp();}catch{}Release(sw);}WaitGone(pid,ticks);foreach(var row in monitors)Kill(Convert.ToInt32(row["pid"]),"sldProcMon");}
            bool clean=Process.GetProcessesByName("SLDWORKS").Length==0&&Process.GetProcessesByName("sldProcMon").Length==0;if(!clean||Hash(root)!=before)return 13;
            string tonguePath=rows.Count>0?Convert.ToString(rows[0]["source_path"]):Path.Combine(cad,TongueName);
            var doc=new Dictionary<string,object>{{"schema","winnsen.locker16029.native_888x14_assembly_tongues.v1"},{"attempt_root",attempt},{"build_evidence_sha256",args[1].ToUpperInvariant()},{"inspector_evidence_sha256",args[2].ToUpperInvariant()},{"root_manifest_path",manifest},{"root_manifest_sha256",Hash(manifest)},{"generated_at_utc",DateTime.UtcNow.ToString("o")},{"inspector",new Dictionary<string,object>{{"id",ToolId},{"source_path",source},{"source_sha256",ExpectedSourceSha256},{"executable_path",Path.GetFullPath(exe)},{"executable_sha256",Hash(exe)}}},{"root_assembly",new Dictionary<string,object>{{"path",root},{"sha256",before},{"read_only_reopen",true},{"open_errors",errors},{"open_warnings",warnings},{"rebuild_succeeded",rebuilt},{"save_api_calls",0},{"source_unchanged",true}}},{"tongue_source",new Dictionary<string,object>{{"path",tonguePath},{"sha256",TongueSha}}},{"instances",rows},{"session",new Dictionary<string,object>{{"purpose","inspect_root_assembly_tongues_readonly"},{"created",true},{"sldworks_process_id",pid},{"sldworks_start_ticks_utc",ticks},{"solidworks_revision",revision},{"solidworks_executable_path",swExe},{"solidworks_executable_sha256",SwSha},{"solidworks_2020_exact_gate",true},{"monitor_processes",monitors},{"process_exited",true},{"monitors_exited",true},{"sldprocmon_identity_gate",true}}},{"final_process_cleanup_gate",true}};doc["self_digest"]=SelfDigest(doc);Write(output,doc);Console.WriteLine(output);return 0;
        }
        private static bool Exact(Dictionary<string,object>d,params string[]k){return d.Count==k.Length&&new HashSet<string>(d.Keys,StringComparer.Ordinal).SetEquals(k);}
        private static bool Under(string p,string r){string x=Path.GetFullPath(p),b=Path.GetFullPath(r).TrimEnd('\\')+"\\";return x.StartsWith(b,StringComparison.OrdinalIgnoreCase);}
        private static bool Same(string a,string b){return string.Equals(Path.GetFullPath(a),Path.GetFullPath(b),StringComparison.OrdinalIgnoreCase);}
        private static string Hash(string p){using(var h=SHA256.Create())using(var s=File.OpenRead(p))return string.Concat(h.ComputeHash(s).Select(x=>x.ToString("X2")));}
        private static string Normalized(string p){string s=File.ReadAllText(p,Encoding.UTF8);s=System.Text.RegularExpressions.Regex.Replace(s,"private const string ExpectedSourceSha256=\"(?:__SOURCE_SHA256__|[0-9A-F]{64})\";","private const string ExpectedSourceSha256=\"__SOURCE_SHA256__\";");using(var h=SHA256.Create())return string.Concat(h.ComputeHash(Encoding.UTF8.GetBytes(s)).Select(x=>x.ToString("X2")));}
        private static void Write(string p,object v){Directory.CreateDirectory(Path.GetDirectoryName(p));string t=p+".tmp-"+Process.GetCurrentProcess().Id;byte[] b=new UTF8Encoding(false).GetBytes(new JavaScriptSerializer{MaxJsonLength=int.MaxValue}.Serialize(v)+System.Environment.NewLine);using(var f=new FileStream(t,FileMode.CreateNew)){f.Write(b,0,b.Length);f.Flush(true);}File.Move(t,p);}
        private static void Release(object o){if(o!=null&&Marshal.IsComObject(o))try{Marshal.FinalReleaseComObject(o);}catch{}}
        private static void WaitGone(int pid,long ticks){DateTime e=DateTime.UtcNow.AddSeconds(30);while(DateTime.UtcNow<e){try{using(var p=Process.GetProcessById(pid)){if(p.HasExited||p.StartTime.ToUniversalTime().Ticks!=ticks)return;}}catch{return;}Thread.Sleep(250);}Kill(pid,"SLDWORKS");}
        private static void Kill(int id,string n){try{using(var p=Process.GetProcessById(id)){if(p.ProcessName.Equals(n,StringComparison.OrdinalIgnoreCase)){p.Kill();p.WaitForExit(5000);}}}catch{}}
        private static string SelfDigest(Dictionary<string,object> doc){var copy=new Dictionary<string,object>(doc,StringComparer.Ordinal);copy.Remove("self_digest");return HashText(Stable(copy));}
        private static string HashText(string s){using(var h=SHA256.Create())return string.Concat(h.ComputeHash(Encoding.UTF8.GetBytes(s)).Select(x=>x.ToString("X2")));}
        private static string Stable(object value){var json=new JavaScriptSerializer();var map=value as Dictionary<string,object>;if(map!=null)return "{"+string.Join(",",map.Keys.OrderBy(k=>k,StringComparer.Ordinal).Select(k=>json.Serialize(k)+":"+Stable(map[k])))+"}";var list=value as IEnumerable;if(list!=null&&!(value is string))return "["+string.Join(",",list.Cast<object>().Select(Stable))+"]";return json.Serialize(value);}
        private static List<Dictionary<string,object>> OwnedMonitors(int parent){var rows=new List<Dictionary<string,object>>();using(var q=new ManagementObjectSearcher("SELECT ProcessId,CommandLine FROM Win32_Process WHERE Name='sldProcMon.exe'"))using(var found=q.Get())foreach(ManagementObject item in found){int pid=Convert.ToInt32(item["ProcessId"]);string cmd=Convert.ToString(item["CommandLine"])??"";if(System.Text.RegularExpressions.Regex.IsMatch(cmd,"(?:^|\\s)--ppid="+parent+"(?:\\s|$)"))rows.Add(new Dictionary<string,object>{{"pid",pid},{"parent_sldworks_process_id",parent},{"start_ticks_utc",Process.GetProcessById(pid).StartTime.ToUniversalTime().Ticks},{"command_line",cmd},{"ownership_verified",true}});}return rows;}
    }
}
